### ISSUE TITLE
Request for previous year documents

### ISSUE THREAD

**Issue by nesslam** [Technology-for-the-Poorest-Billion/2024-ideabatic-beam#1]
@akabla Can you please send over the previous year documents? Thank you!

**Comment by akabla** [comment]
Hi @nesslam. I'll ask the students who did the work last year first, but it should not be a problem. I'll get back to you soon.

**Comment by akabla** [comment]
@nesslam @rb990 @ajb372 

The three students from last year are happy to share the content. I'll follow this up by email very soon.
