### ISSUE TITLE
stl files missing?

### ISSUE THREAD

**Issue by akabla** [Technology-for-the-Poorest-Billion/2024-ideabatic-beam#3]
In the file:
door top modification.scad

there are references to:
        import("/Users/vanessalam/Desktop/Door-Lower Part.STEP.STL");
        import("/Users/vanessalam/Desktop/Door-Top Part.STEP.STL");

Where can we find these files?

**Comment by nesslam** [comment]
I forgot to add them as they were part of a bigger .STL folder where only part of the folder was uploaded. I can add them now.

**Comment by akabla** [comment]
That'd be great @nesslam , just to make sure there is a complete set for the partners. Thanks!

**Comment by akabla** [comment]
ps: please close this issue when you've done it.

**Comment by nesslam** [comment]
ok, thanks!
